services:
  nginx:
    image: nginx:1.27.5-alpine
    container_name: '${APP_NAME}-nginx'
    ports:
      - '${APP_PORT}:80'
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
  
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: '${APP_NAME}-php'
    working_dir: /var/www/html
    environment:
      APP_ENV: prod
    volumes:
      - .:/var/www/html
    depends_on: 
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:8.4
    container_name: '${APP_NAME}-db'
    ports: 
      - '${DB_PORT}:3306'
    command: 
      - --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - takiondb:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASS
      interval: 5s
      retries: 10
volumes:
  takiondb: